version: "3.9"

services:

  webconbps:
    hostname: webconbps
    build:
      context: .
      dockerfile: DockerfileWebcon
    restart: unless-stopped
    ports:
      - "9000:80"
      - "9001:443"
    volumes:
      - ./source:C:/install
      - ./vendor:C:/vendor
    command: 
      - powershell.exe -command "& { . C:\dockerbuild.ps1; webcon-install }"; ping -t localhost
    # networks:
    #   - main

  sqlserver:
    hostname: sqlserver
    build:
      context: .
      dockerfile: DockerfileMSSQL
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "webc0n.BPS"
      ACCEPT_EULA: "Y"
    deploy:
      resources:
        limits:
          memory: 4G
    # networks:
    #   - main

# on win10 > docker network create --driver nat main
# networks:
#   main:
#     driver: bridge

