version: "3.9"

services:

  webconbps:
    build: .
    restart: unless-stopped
    ports:
      - "9000:80"
      - "9001:443"
    networks:
      - public
    volumes:
      - ./source:C:/install
      - ./vendor:C:/vendor
    # networks:
    #   - main

  sqlserver:
    hostname: sqlserver
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "webc0n.BPS"
      ACCEPT_EULA: "Y"
    deploy:
      resources:
        limits:
          memory: 4G
    # networks:
    #   - main

# on win10 > docker network create --driver nat main
# networks:
#   main:
#     driver: bridge

